### ISSUE TITLE
Page - List des Dépences

### ISSUE THREAD

**Issue by florianbematol** [Scholanova/mes_vacances_entre_amis#7]
##### _Frontend_
- [x] Afficher une page web avec la liste des dépenses pour un event
- [x] Pour chaque dépense afficher:
     - Le nom de la dépense
     - La valeur de la dépende
- [x] Permettre de cliquer sur une dépense et d'aller sur la page d'info d'une dépense

##### _Backend_
- [x] Récupérer toutes les dépendes d'un évent à partir de son id

**Comment by arond1** [comment]
Voir PR #32
